#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "tokenizers>=0.22",
# ]
# [tool.uv]
# index-url = "https://pypi.org/simple"
# ///
"""Fixture records for the Kev-0.8B oracle: SystemOne request bodies, read from pinned files or written here.

Every record's `request` is a body the author's `kev.api.SystemOneRequest.model_validate` accepts as is
(`model`, `state`, `questions`; each question carries only `type`, `instructions` and `criteria`). `gold` maps a
question id to the key its probabilities are reported under (`kev.api.question_keys`: a criteria name for choice,
"false" / "true" for noul, the level index as a string for score). Five sources:

* `tv4_000`..`tv4_059` - the first 60 lines, in file order, of transfer-v4 `development.jsonl` from the author's
  repository at tag kev-1.0 (all 60 are MMLU four-option questions; MMLU is MIT). `label` -> gold, `src` and
  `_meta` -> provenance (`_meta.id` is the key the LiteRT lane matches on).
* `tv4x_<source>_<k>` - the first 20 records, in file order, of each of the file's seven other sources (emotion,
  tweet_offensive, qnli, paws, sciq, legacy_holdout, composition_holdout; by `_meta.source`): 140 records.
* `tv4s_<k>` - the first 20 records, in file order, whose question is a `score` (all legacy_holdout, three levels).
* `semif_<id>` - SemIf's authored144 (MIT, `benchmarks/data/authored144.jsonl` at ca3ba65f), each row mapped to
  one `choice` question: state -> state, question -> instructions, options -> criteria {id: description} in file
  order, gold = options[label].id.
* `own_*` - records written here: a support ticket, an incident report, an e-mail thread, meeting notes, a product
  review, a chat log, a voicemail, a policy excerpt, an invoice, an order, sensor readings, a calendar event, an API
  error payload, a helpdesk queue (a top-level array), a flat listing with eight questions, a pasted text that
  carries the delimiter spellings (`<|box_end|>` ...: kev.model.user_tokens rewrites them), a complaint letter, and
  three long states (a sorter log, a contract excerpt, the minutes of a members' meeting) of 1,400-1,900 tokens.
  People, organisations, products and places are invented; no URL or e-mail address appears. Organisation and
  place names use stems that resolved to no A record on .com / .net / .io / .co.uk / .app when they were picked
  (screened by exact-phrase web search, DNS, the App Store API and Companies House; see `names_screen` in records.json; 9 records are withheld and read from a file outside the repository).

The transfer-v4 records are read from the author's file, never copied into this repository; their per-source
licences are listed in `sources` (several are not open for redistribution: do not publish their text).

    python3 conversion/kev/make_fixtures.py          # -> $ZOO_WORK_ROOT/_kev/fixtures/records.json

The transfer-v4 file is taken from `$ZOO_WORK_ROOT/_kev/kev-src` (a clone of the author's repository at tag kev-1.0)
or, with `--fetch`, from GitHub at the tag's commit; its sha256 is asserted either way.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import urllib.request
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from _paths import code_path, hf_snapshot, work_path  # noqa: E402

MODEL = "kev-0.8b"
BASE = {"hf_id": "Qwen/Qwen3.5-0.8B-Base", "revision": "dc7cdfe2ee4154fa7e30f5b51ca41bfa40174e68"}
KEV_TAG = {"repo": "github.com/jaredpalmer/kev", "tag": "kev-1.0", "commit": "6b719c3c3f367295f6ef336f4f751cf5ff970abc"}
TRANSFER_V4 = {
    "path_in_repo": "evals/v4/transfer-v4/development.jsonl",
    "local": str(work_path("_kev", "kev-src", "evals", "v4", "transfer-v4", "development.jsonl")),
    "raw_url": f"https://raw.githubusercontent.com/jaredpalmer/kev/{KEV_TAG['commit']}/evals/v4/transfer-v4/development.jsonl",
    "sha256": "ff374c49c6c9f15f8a56fb274b4a4857d20497eb8dd1ac07ce01560e682a5f2e",
    "bytes": 803309,
    "lines": 764,
    "repo_license": "Apache-2.0 (the author's repository)",
}
TV4_SOURCE_LICENSES = {  # per-source licence of the underlying dataset (Hub card_data, read 2026-10-03)
    "mmlu": {"dataset": "cais/mmlu", "license": "mit"},
    "emotion": {"dataset": "dair-ai/emotion", "license": "other (card)"},
    "tweet_offensive": {"dataset": "cardiffnlp/tweet_eval", "license": "unknown (card)"},
    "qnli": {"dataset": "nyu-mll/glue", "license": "other (card; QNLI derives from SQuAD, CC BY-SA 4.0)"},
    "paws": {"dataset": "google-research-datasets/paws", "license": "other (card)"},
    "sciq": {"dataset": "allenai/sciq", "license": "cc-by-nc-3.0"},
    "legacy_holdout": {"dataset": None, "license": "generated by the author (Apache-2.0 repository)"},
    "composition_holdout": {"dataset": None, "license": "generated by the author (Apache-2.0 repository)"},
}
TV4X_SOURCES = ["emotion", "tweet_offensive", "qnli", "paws", "sciq", "legacy_holdout", "composition_holdout"]
TV4_N, TV4X_PER_SOURCE, TV4S_N = 60, 20, 20
# --heldout: the next slices, never read by a round that chose anything (0-based [lo, hi) in each slice's own order)
TV4H_RANGE, TV4XH_RANGE, TV4SH_RANGE = (60, 100), (20, 30), (20, 40)
SEMIF = {
    "path": str(code_path("codex-conversions", "2026-09-21", "semif-ondevice", "fixtures", "authored144.jsonl")),
    "license_path": str(code_path("codex-conversions", "2026-09-21", "semif-ondevice", "semif", "LICENSE")),
    "sha256": "8162d1c73f925af64453f1ec05ef36d583b3815bf698e60f0d454bd11537e079",
    "upstream_repo": "github.com/TheoLeeCJ/SemIf",
    "upstream_path": "benchmarks/data/authored144.jsonl",
    "upstream_commit": "ca3ba65f142967030ecb453346e94d6f476a69df",
    "license": "MIT",
    "copyright_notice": "Copyright (c) 2026 TheoLeeCJ",
    "rows": 144,
}
SEMIF_QUESTION_ID = "decision"
LONG_STATE_TOKENS = (1400, 1900)
ROW_MAX_TOKENS = 4096   # the decoder graph's context: no row (state + one branch) may exceed it
NAMES_SCREEN = {
    "method": ["exact-phrase web search per stem and per compound name the records use",
               "DNS A records of <stem>.com/.net/.io/.co.uk/.app and of the compound names",
               "App Store search API (itunes.apple.com/search, entity software)",
               "Companies House register search"],
    "date": "2026-10-04 (round 9; a DNS-only screen on 2026-10-03 had passed all ten stems)",
    "stems_published": ["brindlecourt", "fennistone", "ostlebury", "pennimere", "quennick", "wendlecote"],
    "withheld": {"records": ["own_t02", "own_t03", "own_t05", "own_t08", "own_t09", "own_j03", "own_j04", "own_j05", "own_L02"],
                 "why": "four invented stems used in these records were found in use on the web (a book series, a product, "
                        "game places, a fan wiki); the records keep their ids, request hashes and reference numbers, their "
                        "text is not published (own_records_public.json carries stubs)"},
    "people": "given names only (no surname), none of them a public figure's full name",
}
SPECIAL_RE = re.compile(r"<\|([A-Za-z0-9_]+)\|>")   # kev.model._SPECIAL_RE: user text never produces delimiter tokens


# --------------------------------------------------------------------------- request helpers
def noul(instructions=None, criteria=None):
    q = {"type": "noul"}
    if instructions is not None:
        q["instructions"] = instructions
    if criteria is not None:
        q["criteria"] = criteria
    return q


def choice(instructions, criteria):
    q = {"type": "choice"}
    if instructions is not None:
        q["instructions"] = instructions
    q["criteria"] = criteria
    return q


def score(instructions, levels):
    q = {"type": "score"}
    if instructions is not None:
        q["instructions"] = instructions
    q["criteria"] = list(levels)
    return q


def record(rid, source, state, questions, gold=None, note="", provenance=None):
    out = {"id": rid, "source": source, "request": {"model": MODEL, "state": state, "questions": questions},
           "gold": gold or {}, "note": note}
    if provenance is not None:
        out["provenance"] = provenance
    return out


# --------------------------------------------------------------------------- transfer-v4 slices
def read_transfer_v4(fetch: bool) -> list[dict]:
    path = Path(TRANSFER_V4["local"])
    if path.exists():
        raw = path.read_bytes()
    elif fetch:
        with urllib.request.urlopen(TRANSFER_V4["raw_url"], timeout=60) as r:
            raw = r.read()
    else:
        raise SystemExit(f"{path} not found: clone the author's repository at tag kev-1.0 there, or pass --fetch")
    assert hashlib.sha256(raw).hexdigest() == TRANSFER_V4["sha256"], "transfer-v4 development.jsonl changed"
    lines = raw.decode("utf-8").splitlines()
    assert len(lines) == TRANSFER_V4["lines"]
    return [json.loads(line) for line in lines]


def gold_key(q):
    """A transfer-v4 label -> the question_keys entry: choice = the criteria name, noul = bool, score = level index."""
    y = q["label"]
    if q["type"] == "choice":
        assert y in q["criteria"], y
        return y
    if q["type"] == "noul":
        assert isinstance(y, bool), y
        return "true" if y else "false"
    assert isinstance(y, int) and 0 <= y < len(q["criteria"]), y
    return str(y)


def tv4_record(rid, source, line_no, r):
    questions = {qid: {k: v for k, v in q.items() if k in ("type", "instructions", "criteria")} for qid, q in r["questions"].items()}
    gold = {qid: gold_key(q) for qid, q in r["questions"].items()}
    prov = {"file": TRANSFER_V4["path_in_repo"], "line": line_no, "src": {qid: q.get("src") for qid, q in r["questions"].items()},
            "_meta": r["_meta"]}
    return record(rid, source, r["state"], questions, gold, note=f"{r['_meta'].get('source')} {r['_meta'].get('id')}", provenance=prov)


def transfer_v4_records(rows):
    tv4 = [tv4_record(f"tv4_{i:03d}", "transfer_v4_dev_head", i, rows[i]) for i in range(TV4_N)]
    assert all(r["provenance"]["_meta"]["source"] == "mmlu" for r in tv4)
    tv4x = []
    for src in TV4X_SOURCES:
        picked = [(i, r) for i, r in enumerate(rows) if r["_meta"]["source"] == src][:TV4X_PER_SOURCE]
        assert len(picked) == TV4X_PER_SOURCE, src
        tv4x += [tv4_record(f"tv4x_{src}_{k:02d}", "transfer_v4_dev_sources", i, r) for k, (i, r) in enumerate(picked)]
    scored = [(i, r) for i, r in enumerate(rows) if any(q["type"] == "score" for q in r["questions"].values())][:TV4S_N]
    tv4s = [tv4_record(f"tv4s_{k:02d}", "transfer_v4_dev_score", i, r) for k, (i, r) in enumerate(scored)]
    assert len(tv4s) == TV4S_N
    lines = [r["provenance"]["line"] for r in tv4 + tv4x + tv4s]
    assert len(lines) == len(set(lines)), "a transfer-v4 line is in two slices"
    return tv4, tv4x, tv4s


def heldout_records(rows):
    """The held-out slices (`--heldout`): mmlu records 61-100, records 21-30 of each other source, score records
    21-40, all in file order; none of their lines is in the fixture's slices."""
    lo, hi = TV4H_RANGE
    mmlu = [(i, r) for i, r in enumerate(rows) if r["_meta"]["source"] == "mmlu"][lo:hi]
    assert len(mmlu) == hi - lo
    tv4h = [tv4_record(f"tv4h_{k:02d}", "transfer_v4_dev_head_heldout", i, r) for k, (i, r) in enumerate(mmlu)]
    tv4xh = []
    lo, hi = TV4XH_RANGE
    for src in TV4X_SOURCES:
        picked = [(i, r) for i, r in enumerate(rows) if r["_meta"]["source"] == src][lo:hi]
        assert len(picked) == hi - lo, src
        tv4xh += [tv4_record(f"tv4xh_{src}_{k:02d}", "transfer_v4_dev_sources_heldout", i, r) for k, (i, r) in enumerate(picked)]
    lo, hi = TV4SH_RANGE
    scored = [(i, r) for i, r in enumerate(rows) if any(q["type"] == "score" for q in r["questions"].values())][lo:hi]
    assert len(scored) == hi - lo
    tv4sh = [tv4_record(f"tv4sh_{k:02d}", "transfer_v4_dev_score_heldout", i, r) for k, (i, r) in enumerate(scored)]
    held = tv4h + tv4xh + tv4sh
    lines = [r["provenance"]["line"] for r in held]
    fx = {r["provenance"]["line"] for r in sum(transfer_v4_records(rows), [])}
    assert len(lines) == len(set(lines)), "a transfer-v4 line is in two held-out slices"
    assert not set(lines) & fx, "a held-out line is in the fixture"
    return held


# --------------------------------------------------------------------------- SemIf authored144
def semif_records(path: Path):
    raw = path.read_bytes()
    assert hashlib.sha256(raw).hexdigest() == SEMIF["sha256"], "authored144.jsonl changed"
    out = []
    for line in raw.decode().splitlines():
        r = json.loads(line)
        assert len(r["options"]) == 3 and isinstance(r["state"], str)
        criteria = {o["id"]: o["description"] for o in r["options"]}
        assert len(criteria) == 3
        gold = r["options"][r["label"]]["id"]
        out.append(record(f"semif_{r['id']}", "semif_authored144", r["state"],
                          {SEMIF_QUESTION_ID: choice(r["question"], criteria)},
                          gold={SEMIF_QUESTION_ID: gold},
                          note=f"family={r['family']} variant={r['provenance']['variant']} group={r['group_id']}",
                          provenance={"family": r["family"], "variant": r["provenance"]["variant"], "group_id": r["group_id"],
                                      "label": r["label"], "option_order": [o["id"] for o in r["options"]]}))
    assert len(out) == SEMIF["rows"]
    return out


# --------------------------------------------------------------------------- own records: long states
def sorter_log() -> str:
    """A deterministic sorter log (about 1,600 tokens): lane 7 jams at 06:43:05, the sorter is stopped 22 min 24 s."""
    lines = ["BRINDLECOURT LOGISTICS - parcel hub 2, cross-belt sorter S1, controller log (excerpt)",
             "shift: early (06:00-14:00)   supervisor on duty: Yusuf   maintenance on call: Malik", ""]
    rate = [1712, 1698, 1731, 1704, 1689, 1720, 1716, 1702, 1695, 1727, 1709, 1683, 1718, 1700]
    for i, minute in enumerate(range(0, 40, 3)):
        lines.append(f"06:{minute:02d}:00 INFO  throughput {rate[i]} parcels/h; lanes 1-12 active; scanner read rate {99.1 + (i % 4) * 0.2:.1f}%")
        if minute in (9, 27):
            lines.append(f"06:{minute:02d}:41 INFO  diverter D4 calibration check passed (offset {0.3 + minute / 100:.2f} mm)")
        if minute in (12, 33):
            lines.append(f"06:{minute:02d}:17 WARN  scanner T2 no-read on parcel {48211 + minute * 13}; parcel sent to manual lane")
    lines += [
        "06:40:00 INFO  throughput 1694 parcels/h; lanes 1-12 active; scanner read rate 99.3%",
        "06:41:12 WARN  lane 7 drive motor current 8.9 A (limit 8.0 A) for 5 s",
        "06:41:58 WARN  lane 7 drive motor current 9.4 A (limit 8.0 A) for 12 s",
        "06:42:40 WARN  lane 7 belt speed 1.62 m/s (setpoint 1.80 m/s)",
        "06:43:05 ERROR lane 7 jam detected: photo-eye PE7-3 blocked for more than 3 s",
        "06:43:06 ERROR sorter S1 stopped by safety controller (cause: jam lane 7); all lanes halted",
        "06:43:06 INFO  infeed conveyors paused; parcels held on accumulation belts",
        "06:43:40 INFO  alarm acknowledged by Yusuf at the control desk",
        "06:44:15 INFO  maintenance call raised to Malik (priority 1)",
        "06:46:02 INFO  scanner T1 and T2 idle (no parcels); self-test passed",
        "06:47:30 INFO  accumulation belts at 64% capacity",
        "06:50:12 INFO  Malik on site at lane 7; lock-out applied to lane 7 drive",
        "06:52:48 INFO  accumulation belts at 81% capacity; infeed doors 3 and 4 closed to new trailers",
        "06:55:20 INFO  jam cause reported by Malik: crushed carton wedged under the lane 7 belt at the second roller",
        "06:58:41 INFO  carton removed from lane 7; roller R7-2 inspected, no damage found",
        "07:00:05 INFO  lane 7 belt tension measured below specification; adjustment started",
        "07:03:12 INFO  lane 7 belt tension adjusted; test run at low speed 0.5 m/s for 60 s passed",
        "07:04:25 INFO  lock-out removed from lane 7 drive",
        "07:05:30 INFO  sorter S1 restarted by Yusuf; stoppage 22 min 24 s",
        "07:05:31 INFO  infeed conveyors resumed; infeed doors 3 and 4 reopened",
        "07:06:00 INFO  lane 7 drive motor current 6.1 A (limit 8.0 A)",
    ]
    rate2 = [1840, 1866, 1851, 1792, 1748, 1731, 1722, 1715]
    for i, minute in enumerate(range(9, 33, 3)):
        lines.append(f"07:{minute:02d}:00 INFO  throughput {rate2[i]} parcels/h (backlog clearing); lanes 1-12 active; scanner read rate {99.0 + (i % 3) * 0.3:.1f}%")
        if minute == 15:
            lines.append("07:15:44 WARN  scanner T1 no-read on parcel 49870; parcel sent to manual lane")
        if minute == 21:
            lines.append("07:21:09 INFO  accumulation belts back below 10% capacity")
        if minute == 27:
            lines.append("07:27:30 INFO  lane 7 drive motor current 5.9 A (limit 8.0 A); belt speed 1.80 m/s")
    lines += [
        "07:33:00 INFO  shift note by Yusuf: lane 7 belt tension to be checked again at 10:00; carton supplier to be told about weak boxes",
        "07:33:05 INFO  sorter S1 running normally; no active alarms",
    ]
    return "\n".join(lines)


# The long states of own_L02 (a contract excerpt) and own_L03 (meeting minutes) live in the own records data files.


# --------------------------------------------------------------------------- own records
OWN_PUBLIC = Path(__file__).with_name("own_records_public.json")
OWN_WITHHELD_DEFAULT = work_path("_kev", "fixtures", "own_records_withheld.json")


def own_records(withheld_path=None):
    """The 20 records written for this port (own_*), from data files, not from this source.

    `own_records_public.json` (in the repository) carries 11 records with their text and 9 stubs: a stub keeps the id,
    the source, the question ids and the sha256 of the request. The 9 were withheld after the round-9 name screen (an
    invented organisation or place name in each turned up in use on the web: a book series, a product, game places) and
    live outside the repository at `OWN_WITHHELD_DEFAULT` (KEV_OWN_WITHHELD overrides). With that file present the 20
    records are rebuilt exactly (the request hashes are asserted against the stubs); without it the 11 public records are
    built and the stubs are left out, so the fixture of a fresh clone has 375 records instead of 384. The published
    fixture files (models/kev-*/fixtures-kev-*.json) keep every id and every reference number either way."""
    pub = json.loads(OWN_PUBLIC.read_text())["records"]
    path = Path(os.environ.get("KEV_OWN_WITHHELD") or (withheld_path or OWN_WITHHELD_DEFAULT)).expanduser()
    withheld = {}
    if path.is_file():
        for r in json.loads(path.read_text())["records"]:
            withheld[r["id"]] = r
    out, skipped = [], []
    for r in pub:
        if not r.get("withheld"):
            out.append(r)
            continue
        full = withheld.get(r["id"])
        if full is None:
            skipped.append(r["id"])
            continue
        got = hashlib.sha256(json.dumps(full["request"], sort_keys=True, ensure_ascii=False).encode()).hexdigest()
        assert got == r["request_sha256"], f"{r['id']}: the withheld record's request does not match its stub ({got[:12]} != {r['request_sha256'][:12]})"
        out.append(full)
    if skipped:
        print(f"own records: {len(skipped)} withheld records left out (no {path}): {', '.join(skipped)}")
    return out


# --------------------------------------------------------------------------- checks
def keys_of(q):
    if q["type"] == "choice":
        return list(q["criteria"])
    if q["type"] == "noul":
        return ["false", "true"]
    return [str(i) for i in range(len(q["criteria"]))]


def check_records(records, own_complete=True):
    """Shape checks on every record; the own-record minimums (counts per type and option width) are asserted only when
    all 20 own records are present (own_complete), since a clone without the withheld file builds 11 of them."""
    ids = [r["id"] for r in records]
    assert len(ids) == len(set(ids)), "duplicate record id"
    for r in records:
        req = r["request"]
        assert req["model"] == MODEL and "state" in req and isinstance(req["questions"], dict) and req["questions"]
        for qid, q in req["questions"].items():
            assert set(q) <= {"type", "instructions", "criteria"}, (r["id"], qid)
            assert q["type"] in ("noul", "choice", "score")
            if q["type"] == "choice":
                assert 1 <= len(q["criteria"]) <= 255, (r["id"], qid)
            if q["type"] == "noul" and q.get("criteria"):
                assert set(q["criteria"]) <= {"true", "false"}, (r["id"], qid)
            g = r["gold"].get(qid)
            assert g is None or g in keys_of(q), (r["id"], qid, g)
        assert set(r["gold"]) <= set(req["questions"]), r["id"]
    own = [r for r in records if r["source"].startswith("own_")]
    for r in own:
        text = json.dumps(r["request"], ensure_ascii=False)
        for bad in ("http", "www.", "@", ".com", "Jev"):
            assert bad not in text, (r["id"], bad)
    if not own:                                   # the held-out file: transfer-v4 records only
        return {}
    stats = Counter()
    for r in own:
        qs = r["request"]["questions"]
        stats["records"] += 1
        stats["questions"] += len(qs)
        stats["records_2plus_questions"] += len(qs) >= 2
        stats["max_questions"] = max(stats["max_questions"], len(qs))
        stats["object_states"] += isinstance(r["request"]["state"], dict)
        stats["array_states"] += isinstance(r["request"]["state"], list)
        for q in qs.values():
            t = q["type"]
            stats[t] += 1
            stats["no_instructions"] += "instructions" not in q
            if t == "noul":
                stats["noul_criteria"] += bool(q.get("criteria"))
                stats["noul_no_criteria"] += not q.get("criteria")
            if t == "choice":
                n = len(q["criteria"])
                assert 2 <= n <= 10, (r["id"], n)
                stats["choice_10_options"] += n == 10
                stats["choice_2_options"] += n == 2
                stats["choice_null_description"] += any(v is None for v in q["criteria"].values())
                stats["choice_object_description"] += any(isinstance(v, dict) for v in q["criteria"].values())
            if t == "score":
                n = len(q["criteria"])
                assert 2 <= n <= 7, (r["id"], n)
                stats[f"score_{n}_levels"] += 1
    need = {"noul": 12, "score": 12, "choice_10_options": 2, "choice_null_description": 3, "choice_object_description": 2,
            "no_instructions": 3, "noul_criteria": 3, "noul_no_criteria": 3, "score_7_levels": 2, "object_states": 3,
            "array_states": 1, "records_2plus_questions": 10}
    for k, v in (need if own_complete else {}).items():
        assert stats[k] >= v, (k, stats[k], v)
    assert stats["max_questions"] == 8, stats
    return dict(stats)


def render_value(v, indent=0):
    """kev.api.render (the author's flattening of a JSON state / instruction / description into text)."""
    pad = "  " * indent
    if v is None:
        return ""
    if isinstance(v, (str, int, float, bool)):
        return str(v)
    if isinstance(v, list):
        return "\n".join(f"{pad}- {render_value(x, indent + 1).lstrip()}" for x in v)
    return "\n".join(f"{pad}{k}:\n{render_value(x, indent + 1)}" if isinstance(x, (dict, list)) else f"{pad}{k}: {render_value(x)}"
                     for k, x in v.items())


def option_texts(q):
    """kev.api.to_record's option strings, in key order."""
    if q["type"] == "noul":
        c = q.get("criteria") or {}
        return [f"no: {render_value(c['false'])}" if c.get("false") not in (None, "") else "no",
                f"yes: {render_value(c['true'])}" if c.get("true") not in (None, "") else "yes"]
    if q["type"] == "choice":
        return [k if v is None or v == "" else f"{k}: {render_value(v)}" for k, v in q["criteria"].items()]
    return [render_value(x) for x in q["criteria"]]


def token_counts(records, tok):
    """Per record: state tokens (the <state> token included) and each question's row length (state + branch), as
    kev.model.encode counts them: user text has <|name|> rewritten to <¦name¦> and is tokenized without special tokens."""
    def n(text):
        return len(tok.encode(SPECIAL_RE.sub(r"<¦\1¦>", text), add_special_tokens=False).ids)
    for r in records:
        req = r["request"]
        s = 1 + n(render_value(req["state"]))
        rows = {}
        for qid, q in req["questions"].items():
            rows[qid] = s + 1 + n(render_value(q.get("instructions"))) + sum(2 + n(o) for o in option_texts(q)) + 1
        r["tokens"] = {"state": s, "rows": rows}
        assert max(rows.values()) <= ROW_MAX_TOKENS, (r["id"], rows)
        if r["source"] == "own_long":
            lo, hi = LONG_STATE_TOKENS
            assert lo <= s <= hi, (r["id"], s)


def summarize(records):
    by_source = {}
    for r in records:
        s = by_source.setdefault(r["source"], {"records": 0, "questions": 0, "types": Counter(), "options": Counter()})
        s["records"] += 1
        for q in r["request"]["questions"].values():
            s["questions"] += 1
            s["types"][q["type"]] += 1
            s["options"][len(keys_of(q))] += 1
    for s in by_source.values():
        s["types"] = dict(sorted(s["types"].items()))
        s["options"] = {str(k): v for k, v in sorted(s["options"].items())}
    rows = sorted(v for r in records for v in r["tokens"]["rows"].values())
    total = Counter()
    for s in by_source.values():
        total["records"] += s["records"]; total["questions"] += s["questions"]
    return {"by_source": by_source, "records": total["records"], "questions": total["questions"],
            "row_tokens": {"min": rows[0], "p50": rows[len(rows) // 2], "max": rows[-1]},
            "state_types": dict(Counter(type(r["request"]["state"]).__name__ for r in records))}


def write_heldout(out: Path, rows) -> int:
    """heldout.json: the records a layer choice made on records.json is checked on (same form as records.json)."""
    path = out / "heldout.json"
    if path.exists():
        raise SystemExit(f"{path} exists: the held-out file is written once")
    records = heldout_records(rows)
    check_records(records)
    from tokenizers import Tokenizer
    tok = Tokenizer.from_file(hf_snapshot(BASE["hf_id"], "tokenizer.json", revision=BASE["revision"]))
    token_counts(records, tok)
    doc = {
        "schema": "kev-fixtures/1",
        "model": MODEL,
        "checkpoint": {"hf_id": "jaredpalmer/kev-0.8b", "tag": "v1.0", "base": BASE},
        "role": "held-out: never used to choose anything (int8 layer selection is made on records.json)",
        "records": records,
        "summary": summarize(records),
        "sources": {"transfer_v4": {**{k: v for k, v in TRANSFER_V4.items() if k != "local"}, "author_repo": KEV_TAG,
                                    "slices": {"tv4h": f"mmlu records {TV4H_RANGE[0] + 1}-{TV4H_RANGE[1]}, file order",
                                               "tv4xh": f"records {TV4XH_RANGE[0] + 1}-{TV4XH_RANGE[1]} of each of "
                                                        f"{TV4X_SOURCES} (by _meta.source), file order",
                                               "tv4sh": f"score records {TV4SH_RANGE[0] + 1}-{TV4SH_RANGE[1]}, file order"},
                                    "disjoint_from": "records.json's tv4 / tv4x / tv4s lines (asserted)",
                                    "source_licenses": TV4_SOURCE_LICENSES,
                                    "publication": "read from the author's file at run time; do not copy the text of "
                                                   "non-open sources into published files"}},
    }
    data = (json.dumps(doc, ensure_ascii=False, indent=1) + "\n").encode()
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_bytes(data)
    os.replace(tmp, path)
    s = doc["summary"]
    print(f"{path}: {s['records']} records, {s['questions']} questions, rows {s['row_tokens']}, sha256 {hashlib.sha256(data).hexdigest()}")
    for src, v in s["by_source"].items():
        print(f"  {src}: {v['records']} records, {v['questions']} questions, {v['types']}, options {v['options']}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out-dir", default=None, help="default $ZOO_WORK_ROOT/_kev/fixtures")
    ap.add_argument("--semif", default=SEMIF["path"])
    ap.add_argument("--fetch", action="store_true", help="read transfer-v4 from GitHub at the kev-1.0 commit if no local clone")
    ap.add_argument("--heldout", action="store_true",
                    help="write heldout.json instead (the next transfer-v4 slices: 130 records; records.json untouched)")
    args = ap.parse_args()
    out = Path(args.out_dir or work_path("_kev", "fixtures")).expanduser()
    out.mkdir(parents=True, exist_ok=True)
    if args.heldout:
        return write_heldout(out, read_transfer_v4(args.fetch))

    tv4, tv4x, tv4s = transfer_v4_records(read_transfer_v4(args.fetch))
    semif = semif_records(Path(args.semif))
    own = own_records()
    records = tv4 + tv4x + tv4s + semif + own
    own_stats = check_records(records, own_complete=len(own) == 20)

    from tokenizers import Tokenizer
    tok = Tokenizer.from_file(hf_snapshot(BASE["hf_id"], "tokenizer.json", revision=BASE["revision"]))
    token_counts(records, tok)

    lic = Path(SEMIF["license_path"]).read_text()
    assert SEMIF["copyright_notice"] in lic and lic.startswith("MIT License")
    (out / "LICENSE-SemIf").write_text(
        f"The semif_* records in records.json are derived from {SEMIF['upstream_path']} of {SEMIF['upstream_repo']} "
        f"at {SEMIF['upstream_commit']}, distributed under the following licence:\n\n{lic}")
    doc = {
        "schema": "kev-fixtures/1",
        "model": MODEL,
        "checkpoint": {"hf_id": "jaredpalmer/kev-0.8b", "tag": "v1.0", "base": BASE},
        "request_form": ("request is the /v1/systemone body kev.api.SystemOneRequest.model_validate takes; gold maps a question "
                         "id to its kev.api.question_keys entry (choice: criteria name, noul: 'false'/'true', score: level index)"),
        "tokens_note": ("tokens = kev.model.encode's counts with the base tokenizer (Qwen/Qwen3.5-0.8B-Base @ dc7cdfe2, "
                        "tokenizer.json): state includes the <state> token; a row is state + one question's branch"),
        "records": records,
        "summary": {**summarize(records), "own_checks": own_stats},
        "sources": {
            "transfer_v4": {**{k: v for k, v in TRANSFER_V4.items() if k != "local"}, "author_repo": KEV_TAG,
                            "slices": {"tv4": f"first {TV4_N} lines (all mmlu)",
                                       "tv4x": f"first {TV4X_PER_SOURCE} records of each of {TV4X_SOURCES} (by _meta.source), file order",
                                       "tv4s": f"first {TV4S_N} records whose question is a score, file order"},
                            "source_licenses": TV4_SOURCE_LICENSES,
                            "publication": "read from the author's file at run time; do not copy the text of non-open sources into published files"},
            "semif_authored144": {k: v for k, v in SEMIF.items() if k not in ("path", "license_path")},
            "own": {"license": "written for this port (same licence as the conversion code)", "names_screen": NAMES_SCREEN},
        },
    }
    path = out / "records.json"
    data = (json.dumps(doc, ensure_ascii=False, indent=1) + "\n").encode()
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_bytes(data)
    os.replace(tmp, path)
    s = doc["summary"]
    print(f"{path}: {s['records']} records, {s['questions']} questions, rows {s['row_tokens']}, sha256 {hashlib.sha256(data).hexdigest()}")
    for src, v in s["by_source"].items():
        print(f"  {src}: {v['records']} records, {v['questions']} questions, {v['types']}, options {v['options']}")
    print("  own checks:", own_stats)
    print("  long states:", {r["id"]: r["tokens"]["state"] for r in records if r["source"] == "own_long"})
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
